---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/ks.yaml
components:
- ../../components/namespace
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: cert-manager
    target:
      kind: Namespace
