---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server
  namespace: home-automation
spec:
  storageClassName: nfs-provision
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
