---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  namespace: default
spec:
  storageClassName: nfs-provision
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
