# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Vc+A/6OLJ5OH8WZJVOxPFfo3s//KITX1ltr9ddytcGY=,iv:upLNqMX5oU9Vuk52HJBi2D0EuHdbf9IaVEVr7cChNgo=,tag:jZ3GHpqiIG4DYUEgA4DnfQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VGhnc2piUDhLYkJHZzdv
        SnJRSlhvamZMMlpySXdQSCsyTWhuNzMvWEhZCkVPU3VKRTgwU1hERyswanp5TlJ3
        SGE0aTRFSnVFN3dKWWpEelF5K0ErWUUKLS0tIGJLanBHWVcvd3VrK2IwVDlIOWJC
        UUtXMVNUV1plTjE3OXVFMEdIMnErUVUKp2Gonn+ooh9nDrrn/2UIO0GN4h0Wr91z
        59Ip1L0Z+fdySODGd1+8bnSQ4/9b7moo3va4ZU2io6jVA8uZtz9bDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T21:54:21Z"
  mac: ENC[AES256_GCM,data:/YtXOo8ByEBAwUlXrxad2pod+UCknUsxeuat4UUDW/DokZI4TUUwRkxUkGMUIUuIvFVWgSWLAy2dXUs3D/xHaKUtLQWobELS4glv38mggjdUOiDADW4huxJBqKDDKAzy1p4WVtgsAwsbCedv5SGYaPsFoSeqByHqfE/Yhy3oehw=,iv:ooghff2pzLQxj215ORMmT+/kYhcihOD54mhVnNKrGQ0=,tag:oJH/aA4XGa4JJckceKGUPg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
