# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:8+zXsvZLtaWVrBKsDig/fHUJYUtLX+LuFlOuDgnq52c=,iv:18LosdA3YF2Vy1uz+c7i7AyEUaxjDizPB66jch5w2dU=,tag:oAuog7fJ7rafP1liwGRKSg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdGFURGo4VmpUS29DVFVR
        d3R0Ylpzcm5IS212WkdoemtVbm9JYWhzcUNBCkhjbHBoMnl5MCtGbDZNMEdBODlk
        WVhWdVNjNC9qZTRXcVNmaTJPRUJNWDAKLS0tIGhJS2xYR3BXNXFuK3E2dzdONTZ3
        c210bXVFT3BWamxKYW5oNXR0OXVWckEKlneGAHjEf1Eo1zdHahbE+oCxRg46Hqs+
        yQBwtmJf8xKGX0n+42KKcy9cR/7I4FFlhpH6Qyono4lFjzY/a9q9Nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T16:40:20Z"
  mac: ENC[AES256_GCM,data:4UOML5TG1ONrPdkxZTHh2tI2GurkOej1UCqHAJrz8+sDKwsP6TAg6wt9S8az4wAlDgWnp5k8cfs0IdGZ5O7JriAbFftD1cLFECSnESACBRoza3TZ59Xpmj87X39ibskWokMvwtfjtZkWp7WJ3vKdG41aWRgSqzWdLwxGVL3niP8=,iv:b8e/9HLev8Hg3WcVy15b+xS/aTRyIoGQraPlOWChQeY=,tag:I5X13hUE7MlSHTqAWNu7gw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
