# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:AyhheIHx9VzUpM6NP9xD0R9m7myGiKYxvUlA5lNDaW0=,iv:D9ylnI4ERCQ6+WjiqhFjLkTv2LTwM7m8dxNsYSvJ2ZM=,tag:ivZWdAiAzBpydgEe+/yoFQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVDVPNUtnZkdhdTVOMXAw
        UitFVVJVcU03SGdyMW85T01XQkVwclQvU240CkZqUlgvUU9ybUZrVXNKQzJHbjB3
        aVZWUEIvYXhqdkF0dTN2OUx4akNid3cKLS0tIGttUHhGQ1hvanVOeE1vbFRFbFdn
        UFpubXFtUmR0eTVnVGIwMVBZd0dPTnMKx7lhf4Tkenr2XRgRvcQJap1BpBk1Yo9s
        sNBKlLooOnHCeTJ+fIQMIqNf3OUMbLPhovfV+iQ+7YMpV3B76XJ+sA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T14:27:16Z"
  mac: ENC[AES256_GCM,data:AiFwWvyplEgyyI9vQRE6LOTeS9NKi16hAUHkSsRePj6eVsiT+zYI0tSQRwNwE2BtNrqnUQITDG4096tH/X4i9PP0+B5os6IdE1SZ01XsMB+MVyIjJNapx1RzsvGByaVNw6/QqK3kaZKtOPmrisljyIWKEm7Zax98Hr7xW8DeEQA=,iv:6ryX5P68fQpO4ndfbH6QkZl/VC16ScHpEJ+rlkv2rSs=,tag:M0X3hXSyu+Mfklj6tJaWEg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
