---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseeer
  namespace: media
spec:
  storageClassName: nfs-provision
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-cache
spec:
  storageClassName: nfs-provision
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 15Gi
