# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:qJbVBz1cybz2kEHBgkqqlGwyvvWMlkj6Mzu61H0PupPONgq8,iv:j9apsiVWQCoc4R6r8j8hdG+/+IakI0mSgNxlol6U76Y=,tag:mikKzr6NCjx0tSatj/hdQg==,type:str]
  credentials.json: ENC[AES256_GCM,data:JK32AgKOtExjtZuLVywPufY4TrQBu//hFbnopGeoxysN+wGg10Hj/0VLfopfv6S/hXAwA2NDFY6DyZt/BFzaHtLU9/cStAHC0CvbexkfD6Jo/Xxqy6NB0cNeaw49I+k8WHy1jSTQSGpAG3zg7e6QLW/tyDqLpDY85OXNBuRyW6ANsufxCia2+3pgIGygbqGg9eizYTYvYGdN6qfhXJVL28HJIsk6bm02u5MjUSV1ZQ==,iv:MEPvEkQrxl+uNMNfCWoTS7JaVhv5Ooqctu09DKI6yX4=,tag:L13hIWy/z0Tz+TKZMfVy0Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMDkrU2lQTU1HRE5nZnhu
        eG5wTHEwdEVjeXBSZjV4WCtKVkRFTW55Um0wCjRZNXpMTnZmK2NnbnVLR2ViUW5E
        RzBQaHQ1QlNuOGlVQ3Bnb05oaWxGNmMKLS0tIGUrOWtCd1c0YWxkQnJQS3pSSDdj
        eDBtaW9LbEhGeFhTQ05UbmdIOGJUdG8K+LniWmGdTpB94CCV5fR8S6DmqtSLsC+O
        m0x/OpBWi9Eh+5uHdpTIpS7k0yf6DW5UTwqEtYi1hCctkvpsz4vZ7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T14:27:16Z"
  mac: ENC[AES256_GCM,data:Pa9ve6cXhkXpqvU/n/w0OxhedPHcbBGvk+EtAyzLdljcHWxLxxm1ZLE4B1Kp38Ok39SaY744sqg4EIsqvHQjNZId7ptZ5Rr9yCO7uVprxpuiUf9iS+XfzaIrr+FhBv4y851rMRNErjtXpKeyQno8cKrgA2B/ZEJpKLSquElYaiI=,iv:HLIw9xe3JdHM0PDSS+BXxsNfiwvfWVh9WJHEkVS+3MU=,tag:jqqE8ZZrpFUhyS6SUGOBgg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
