---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
  namespace: media
spec:
  storageClassName: nfs-provision-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
