---
autoDirectNodeRoutes: true
bgpControlPlane:
  enabled: true
bandwidthManager:
  enabled: false # https://github.com/siderolabs/talos/issues/8836
  bbr: true
bpf:
  hostLegacyRouting: true # https://github.com/siderolabs/talos/issues/8836
  masquerade: true # See https://github.com/siderolabs/talos/issues/8836 (forwardKubeDNSToHost)
  tproxy: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  id: 1
  name: "homelab"
cni:
  exclusive: false
enableIPv4BIGTCP: false # BIG TCP is not supported with legacy host routing" 
enableIPv6BIGTCP: false # BIG TCP is not supported with legacy host routing" 
# Pod, service, and load-balancer IPs are allocated from a publicly routable CIDR.
enableIPv6Masquerade: false
endpointRoutes:
  enabled: true
hubble:
  enabled: false
ipam:
  mode: kubernetes
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 172.22.0.0/16
ipv6:
  enabled: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: false # https://github.com/cilium/cilium/issues/28985
loadBalancer:
  acceleration: best-effort
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
operator:
  replicas: 1
  rollOutPods: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
socketLB:
  enabled: true