---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudnative-pg/ks.yaml
  - ./emqx/ks.yaml
  - ./minio/ks.yaml
components:
  - ../../components/namespace
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: database
    target:
      kind: Namespace
