---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome
  namespace: home-automation
spec:
  storageClassName: nfs-provision-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
