# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Em4K3WKYXe/3pXnNDuMyzP6WiD1DpjX1fQBy83YdrebEdfF0n+2sBA==,iv:LKbSuhCBEMjwdf8aeccmvbcjz1JG4a2S1tXrVBQF5Ow=,tag:XQLrRl05H4MMrwWPZR5jVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY2ltVDh3S0U5SSttUjJN
        WnVWNHZ1UmVuWmxYZXQrU20vZ21Pb1ZhVWtJCkN1UEVhUHNuSjZ1eGVUNEZadWxI
        VFNpUUpwc05qVmdXcjJhVWwzZmlNb0kKLS0tIFFXSzNzTmhvS2dJbUxPY1pPYkt5
        SlpNdVZtUVBGaHFsQnhrUlROMzRkaXMKqZ4bayOBNQvRnH6tv2iqUSfQBhEZB9k5
        228K+YbBiCopk2DJ0whsRTQ+nV/gZbjuTCWZ5DdQYTAgPI2bBAmdGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T21:54:21Z"
  mac: ENC[AES256_GCM,data:IrpR+SLThfj24Xw7O5+RIAZS/duWmkdZgeUnRtszdWT+TRClalBteByZWBjnxowq1wxUUUQs9yQ+E7LMfNbwPjcPDvw1XDGZSM3+NKdD9EEM3ZfQdPuX8b+rhWkzp/IudaWfWOqXZKn1zkAHx6MKgYoy90+9xDR6rZx4DcxXBE8=,iv:G231QVUyUk2hi4KJn8UmkF+oQZ6ddPFLlE411Nhs0b8=,tag:MPQbG+D911nqwg+0thzz2A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
