# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:lipKu/3+AKS3W9BqUAeJK12B6yJMwVuzb9NZs7Io+RCufRD8hmU/Lg==,iv:+oeqYpbskTVmG/d0WFk8O4ifK+BK9VKmWvhKFY31Czs=,tag:sOBEHXrF0t8/+3h/Om027A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd2V4allLOWdEVFBIR3dX
        Qjl0Q09OM1FOOFNtcjB2aUdIWE9jVTBTV2w0CkI3bHJzbkd6S0VhZHNiNnhOWEt0
        eFVwNTFlbG5MZVdHem9yQklnSVZWazQKLS0tIEhiZjRSUVRRMHJUQ2hsK1VuREQ2
        TStScEdLV0dId2ZxeG13SE0zdW43VHMKZp8N/GbnAj9o3UbtDUKuo+cnpwtR5Tim
        L3Fp51gto2ftF1ERM8v1wm7l5Dfpno+r3uiLh9v6tw/P3ipMwl39pQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T16:40:20Z"
  mac: ENC[AES256_GCM,data:s3HXSkiknGw4wg0CkK4xye0BbxdA01Ba1aLg19LtGmtD6gR/IJ6203VSFK1ikW0pfR5pdMhZ4AhIk7yulVgKGNBcQQlWUXnB99XEw5Fdyoij/jy5KjcJOa4Jzn81k/RWWE224R/UqIy5FJbwcfBLrdmn8XMymhKuyBAV9Afi8yA=,iv:LBZECd40q+M1d/aNlHaTXf6Iw0NmUBknHcwPl7N8+hw=,tag:Fi+ktj3FzAjqmCqg5KBM7Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
