# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:wdl8ILQVTTmHury7+9d+PTqzxGy1/6/F6Z97n4/M3sr1KjkhP8O+tw==,iv:tCL0jB1//7kYS99yzmP9NK7V/koSmQZmz4NG94CIuTo=,tag:Cv5VrNj73SB98Tv01/CTFg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQTRVTy93VFRCMVRwSXhy
        aUFJdlFoYVVMK05MMXhiR0ZzckZxaWUwMmtjCmg0NzhaL1VrS2pCL0tFUXNsRisw
        ekc5UjJRNnpUM1QxMW9LaFoyb2I1S28KLS0tIEFYRmEwM1poMS9aQ0FWdE9GNjBE
        TjZGYlg5bDlMOHhzeDFKVlBFVWdLMjAKpFVQa2b6/Oq6ROZhyhCfoSN7KexaGzWC
        L9MkAK8Xaa3L7onYwmEcH/cgI58PyhiSj5WqGjY0a42Hz9fy1gKtAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T14:27:16Z"
  mac: ENC[AES256_GCM,data:AJz0ezzkr6zEBASn5ddh+4PuO7UHvWChfLP6PLxTCQhVIBkWgUPX7fSfRoOmSf4NEW2BqyMAaQwCP/2dkUeGDQLSl0s9VTauqUzk++OEkBHlIIZICjIVyrF4N4f4jE9lIH51fKJqXGJcsZ83m/KgYffo3ib+G9PjbJkCneldp4U=,iv:/0aNAXJLHMqZkZPKO18FLIP0bKnc/1S/r2k1Ltnt0AU=,tag:uFK6Ml1iNjay7uUV1ZHh1Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
