---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omada-controller
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mbentley/omada-controller
              tag: 5.14@sha256:4b90874dc2e6900d9c1e1572af8a8eb0dd92ebf634dce6ddfc71d98a9cea1b09
            env:
              TZ: ${TIMEZONE}
              MANAGE_HTTP_PORT: "8088"
              MANAGE_HTTPS_PORT: "8043"
              PORTAL_HTTP_PORT: "8088"
              PORTAL_HTTPS_PORT: "8843"
              SHOW_SERVER_LOGS: "true"
              SHOW_MONGODB_LOGS: "true"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 500m
                memory: 1200Mi
              limits:
                memory: 2000Mi
    service:
      app:
        controller: app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${OMADA_IP}
        ports:
          # Docs: https://www.tp-link.com/us/support/faq/3281/
          # Management Ports
          mgmt-8088-tcp:
            port: 8088
            targetPort: 8088
            protocol: TCP
          mgmt-8043-tcp:
            port: 8043
            protocol: TCP
            targetPort: 8043
          portal-8843-tcp:
            port: 8843
            protocol: TCP
            targetPort: 8843
          # Device Discovery, Adoption, Management, and Upgrade
          eap-v5-discovery:
            port: 29810
            protocol: UDP
            targetPort: 29810
          eap-v4-discovery1:
            port: 29811
            protocol: TCP
            targetPort: 29811
          eap-v4-discovery2:
            port: 29812
            protocol: TCP
            targetPort: 29812
          eap-v4-upgrade:
            port: 29813
            protocol: TCP
            targetPort: 29813
          eap-v5-manage:
            port: 29814
            protocol: TCP
            targetPort: 29814
          eap-v5-device-info:
            port: 29815
            protocol: TCP
            targetPort: 29815
          eap-v5-remote-control:
            port: 29816
            protocol: TCP
            targetPort: 29816
          init-check:
            port: 27001
            protocol: UDP
            targetPort: 27001
          old-init-info:
            port: 27002
            protocol: TCP
            targetPort: 27002
          old-db-access:
            port: 27017
            protocol: TCP
            targetPort: 27017
          db-access:
            port: 27217
            protocol: TCP
            targetPort: 27217

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        className: "internal"
        hosts:
          - host: omada.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: 8043

    resources:
      requests:
        memory: 1200Mi
        cpu: 1200m
      limits:
        memory: 2000Mi

      config:
        type: nfs
        server: ${NFS_IP}
        path: /config/omada/data
        globalMounts:
          - path: /opt/tplink/EAPController/data
      work:
        type: nfs
        server: ${NFS_IP}
        path: /config/omada/work
        globalMounts:
          - path: /opt/tplink/EAPController/work
      logs:
        type: nfs
        server: ${NFS_IP}
        path: /config/omada/logs
        globalMounts:
          - path: /opt/tplink/EAPController/logs
