---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Amsterdam"
  # Dependencies
  NFS_IP: "192.168.0.7"

  # System
  K8S_GATEWAY: "172.16.20.10"
  NGINX_INTERNAL: "172.16.20.12"
  NGINX_EXTERNAL: "172.16.20.13"

  # Services
  POSTGRES_IP: "172.16.20.21"
  MQTT_IP: "172.16.20.22"

  # IOT
  HA_IP: "172.16.20.30"
  ESPHOME_IP: "172.16.20.31"
  MATTER_IP:  "172.16.20.32"
  MATTER_IPV6: "2a02:a446:fe50:cafe:2::bad:beef:1"
