apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:zgdcOVCyuTeMCFlxAQ==,iv:yxvnXMapr1uakUEuCUSWw9A0ei98Avi0d9J5PuIuXuc=,tag:qwU3BzEbu3Ft6dcEh9VHBg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:4PCl99yYZYnfKWJBb2QSuxg=,iv:InO0jfSUoEueWPcShQA2cW+tIZdDs/HqMwqOS3AEpY4=,tag:xZleIox3azVrI4Sb2nH/HQ==,type:str]
    MATTER_IPV6: ENC[AES256_GCM,data:XOoDnLZqlyTvgsdL0pfqty1nZrwY1PoT7wgJbldwOhjN,iv:lat2sYoCgSiJIWFGdVwS1rqVNA9IkmKk3q6g1+FoNzM=,tag:v9YM6C8KM/0U8KUj8QJHSA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:9wMlW8UOIB+UwKonntvNvMXMsO1KJG56Y6pPchXuqUQPs/+5,iv:ANHgGWienpHdWeIfLexeyUXzg2ms0+llWvpTxl63CgE=,tag:wSICVaVgt6Ck6suyU5c3LA==,type:str]
    CLUSTER_POD_V6_CIDR: ENC[AES256_GCM,data:hzLIe7Bjv/BIk9/RI9RcxTI38OPeX80GbvQ=,iv:Y2CVTtZwOwDffT78u1NREaApaXKtgcSvC2GGxuaYE9A=,tag:RX6h1rAQqL/Ii/rLUn0sWg==,type:str]
    CLUSTER_SVC_V6_CIDR: ENC[AES256_GCM,data:VHJlHej3wR5CeGoAWpIvtugIjZqq3v3j7XCA,iv:ov3LMUORceGKUQISx7W4AWvyexed5XU8nUqS8ipDSX0=,tag:hjFTK35B8FYDTwwFiDbZiQ==,type:str]
    CLUSTER_SVC_V6_PREFIX: ENC[AES256_GCM,data:NgSKeyXe/zwBcU8hkatypR1UsYK0,iv:C2M89v+/uV4rv5e/iJXcRIYxBjTqWCsN5CQm1r0UPqU=,tag:48ZvNBd54kgbLnep0tuE8g==,type:str]
    CLUSTER_LBA_V6_CIDR: ENC[AES256_GCM,data:vMe3geBttwKdOO1+TwkubbF89tufjIZUNgds,iv:smsepAlnKj7vfac6l2ps8jQAs4CPnKNljWAHkTszHLQ=,tag:sfbjThf23nIcDRM+1wmT7Q==,type:str]
    CLUSTER_NODE_V6_CIDR: ENC[AES256_GCM,data:HU7y3x1Y/vvPBYLQF+eoAIqogQ==,iv:MdwumvK2fk8Ud5KSaNbLafoHdP0vFpbkXXUu5PddWX0=,tag:tNrejlTyReX7ZXveLt+nLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZkM3b1YxZis0dUkwditI
            ZVpvZlk0RllEdk1sc1NhWHFDQUEyN1dIcEdRCkNvOUhldFpVNkJVYVpxbmMrTllK
            c21rVGIxUkgydTUvbDRPL2NxMHpITncKLS0tIEVLczkwZURtZDFha2FBNUM2RmZ1
            dThJYU1oUVNEYWFrangzdzMwdW5hem8KjlSDFGdjl0t5ym0n5CLBibKxZlx9gwPd
            RuMKRAW97oteyauMpGm72ZOS1jjWZSmyR7j1X6Z8tm69BplkgLt2/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T19:02:36Z"
    mac: ENC[AES256_GCM,data:DdyNXZ8enFo/NW24kbrmzKqu0SS4jUqpzpGrie4gfEmgfXeJgH/Kk8A30kU4RfhA5diGu7KFukZPmbGX7ppFy4Tk4orfHBbvrQyQfalwkHe6Ru86Pri8qSmwK7ZuZ6e2/i8mdnVRCc1I/1WNN1vVCVkBJWTrTl4fGwswsTtx5Ug=,iv:2hbJb34TEPV3vlfXNJ+iIx9sySGB0BJcPnN1Dxn1Cks=,tag:LgjvxlFbsG2IHrJw+JZOtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
