---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gha-runner-scale-set-controller/ks.yaml
  - ./gha-runner-scale-set/ks.yaml
components:
  - ../../components/namespace
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: actions-runner-system
    target:
      kind: Namespace
