apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:radXFPt0H+y5hH7sTVWePQcBdC/M08gATUttY0xN1UGLxoMaNKi0mQ==,iv:005aAnha/byNQZXQU0L1K4opZEgD8ymI89K8ffYatVE=,tag:ocGOYa2c859ISN9bql352w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QmkxTFRRcTVyRE1VdzlI
            MmRXd2YrU21nV0gvdkQrMWlXVTB0ejVWVlNvCkVyelgxbDJ5K2tDR2ErZUNDYU9B
            dnQ4UXVDMXV2Yy93bXpxOGhCWGtveHcKLS0tIE9PemZrNDVVVi9QdjJIWjBpRHc2
            Yk1WSGhOdTdzTDdQMjJaQjBxS0t0cmcK81Fw9tCq17qumcVDaBOQ3v43HWx+M9Lj
            D/PDCEpxA0T2Hu7wmh10OczqswB+z+BkeIWNPjMMEkxXvcDRPIVvWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:32:55Z"
    mac: ENC[AES256_GCM,data:ivnAem/ketHfxjUy6cQ273BF0Llg80Adm0h/6Vy0ox4UPT6srX6fhrWgqbxxu5614+17YVsNov2PIGHKza0jV1oWzNaH+tbiGyK9aMUVUmXy69jiONaTNjVnqV/1YWVKzrGNJBXVCFGxNPPawbpSnT2eKi62gFRaGnshQqO04iQ=,iv:0pcVBuezVuVP7R1Qm0HAezvh72OPANXeZ9+3cgqeKpA=,tag:M+0JVha77SClClPznUr31Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
