# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:vpPZi3NefwRDZU5RM3NjuUfFVaZzHUyBBZA6w0o+u6A0NRCAXjJ/wQ==,iv:V9BVmWaOfR50lCDYj0f8+P/SKG59icbtwL19OHBqDJ8=,tag:RYaXXD/i6aVL8xziupMYBQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTnU2UTFmZ09UNDRaRHpr
        KzJSTWhpQnFGVFN2c3prbmJ4dFllMmpsWGhNCmNscmt6ekt3UWo1RHNZSStaOEJy
        Z3puNTRMMGdad1RReGduSjdWdFVPRGcKLS0tIExIU0c3RnQvaGNyLzZyRmZvdlpj
        T3dCcVJ6N3BDd2FaMktEN3lpbC8zUWcK23R9HOP0DSRUMOBDyytLjshqGvm1WZO5
        myaD4D3WAQnKoSZloinnTCEK/4nT9hBoFFVOpkBq6MrnUeHr9yg+Fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T21:54:21Z"
  mac: ENC[AES256_GCM,data:elvWFGeFjVPQ/YujPN+1MuRodzQvUbZsL+r//VNvrcjMxarnaFsOwQRZOX+mhIDnGnvuFGGBzMlpuJk00mxjPauBvTtXCay570L3Bwzsj0oeyQk2k0l0KcQwZkT4YqeAT4PLf+XSuSTHH3qTDqNawV4W6g2JymibSpAuNCr/L2w=,iv:+uZUAjOHicMvZ/XGlROh+TZ2FyKI1qr+UXx/kyLu++4=,tag:FyFTj8nT7cHgZbADm8cNEA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
