# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:EdccM/7wvGSQLR7G/2NaA6Jd9cJG3KjJfpOyarxWZtJeHx2yNLaypA==,iv:bu+m854AuwnaY97Rj5vHqF8CdvuIa2sb/zZkAngDwUQ=,tag:m2ipPMQ4g4zGrnDot2u69w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWjVXN3Q1OUJORS94cDFX
        Z3p3MlVuVVBKWnpTWXBRbXBtWFZUYUVRYmlrCndmb0U5MkJZTzVaeTFtbkRGTVov
        NlgyT1prWXJXMEVXckorSndMdnUyUUEKLS0tIE45clVjWjcyZUxjMWlpTVQ4Tkcr
        SG8zRlpEeHQ1YTZrMFJiZUMwVmwrbXMKMNc1zL+Rea4ud62/2RewIrksWdaaeH0k
        KAIGxnZv3sb2gl/M6EAlLluTYfh0Uv0/3Xe5dDW1uq7dhHeTl8dOQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T14:27:16Z"
  mac: ENC[AES256_GCM,data:YBZ/O6zdDRW7g8aP1AQS1x7Py6ZPERVbUvlGZJA0atwCfp2aSSRisQhr0voapOgHsj5QZO2x4hlrClSndOHmdibV94IkHtcUeJgGMOBz2ftFsotKINSLk3M65hxkKRG8eab6YaB7Gbt2WM3e2uzB6Xj8hTV+km9z376GaNmtLN4=,iv:1KY4ox/AfDNcDloA2FZVuTInp9C/5LRNKPOzQPYZ2VM=,tag:MDKcIOOp4NxP63yDAqU88g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
