# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:TKw3iCO1JCZSzCdVNQi0TWInnnqifJY4yls5hyPr8fXVZkX1NIB/tg==,iv:JiS0kQj2CqJZ0gunySFhyhaF3Pzi5diEpvXbDJoJA0E=,tag:tly99m3/sLG9EJgt3N8PHQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYkF3b1NGWFhBb3piQVYr
        NnF5cWJ4TlJ4RitCT1VQalJVR3UrTjIrYWprCmhNNUt6ZWZJbTZZdFlQS2JBOC9y
        bmVINmtYYktMM0RLVnNDYjNmd2hjZ1EKLS0tIFI3eU85MXVndXVHeXlyVnFEeVpX
        bmtnM0FTeWYrQys0bzVjdHJEY01YcWcKE9e5DqKlEz8ImizN49BRTj+IBUSFiAki
        bM2iH4Zixt1MpZ43iNl1FZymHwDp8l7475UyIBC+1uI/jbZ4BEpOqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T16:40:20Z"
  mac: ENC[AES256_GCM,data:LzmxziUd2BpnbnSEZ3VMQAldhln60Ufq25NOl+reQubofGmVpTVU2Q5oR5pYHDsFID0xtNaitJP6eL8dlp1JRZ3CJYZYH1ngg1IYRXY/uA5oFl4fzSmtWNpYzIkKufbxm1EU/FK52aXWezF5V7YrS/psPsu7/veSoA1yp8WMhic=,iv:z0uxfbEXvYxFvEqYYS4gJqaH0m9d42p9tlc+MPorx8k=,tag:lr5a9dqu9La4Izgan8WCNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
