# https://docs.cilium.io/en/latest/network/bgp-control-plane/
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
    name: l3-policy
spec:
    nodeSelector:
        matchLabels:
            kubernetes.io/os: linux
    bgpInstances:
        - name: instance-65001
          localASN: 65001
          peers:
            - name: peer-65000-opnsense-v4
              peerAddress: ENC[AES256_GCM,data:s0uAkk3jKAhoioY=,iv:x1GPP3t6g+15FfTO6gHXfBLy+LwdKp11cLyKqUtYTPA=,tag:CWjO6wUPfCpjilUeMBfapw==,type:str]
              peerASN: 65000
              peerConfigRef:
                name: cilium-peer-v4
            - name: peer-65000-opnsense-v6
              peerAddress: ENC[AES256_GCM,data:vlO4WvlkZXw1SyFfQgRPUIs=,iv:JdKBUS12wanSoJE/Tc0hIoXHkTxQ9Xbo1j9/5rpoBZs=,tag:vljVQ8IqyTB3jl4FlB3yVQ==,type:str]
              peerASN: 65000
              peerConfigRef:
                name: cilium-peer-v6
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1KzE1R3FsVFRrUXdUek4r
            UVJoQ0lvS21wV3VxRVpnVE1MMHgwcndzQmxrClZpOUZmWlVtMGhTY05zQTNGYnRx
            c1F6TVpZNEg1aExmcGhFL0xJTHA2OTQKLS0tIEtqcWt6aHNEVTFUZTAzZGdTTHRC
            aXBUUE1mNG1oWDZYTnpjbER4ZkdPcTgKRD3YQK0iECzYiUlPmkjWRZfoeeVcywcq
            m0rAG0+2pFb/PSo3mLUSp+fJnWgBtCgxu/Hf4zb4HE9LsbDyNlR1TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T18:23:55Z"
    mac: ENC[AES256_GCM,data:1r5sw6fN97hiPstj3yzf7663Z/u5KkHa3BFuGOBsVHvWYFGuDG9h6eeMXgcYknoc/y2Wmx28RE9qmqCb+jDl4jGf4Cli9deX6AgNMTjr7Tnf8W8PF4OEXG/KAA5hsAsFO/GOVTPq2CFTokYmbnW1DRuyXX37XLTxY/PgLTLb/UI=,iv:g7dxBRowszWgXgio5O8375TgKWcyK2d0hci9k+FU+Iw=,tag:saCV0y4RA+wJ/dilkRiZIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|peerAddress)$
    version: 3.9.1
